#!/usr/bin/env python3
"""Generate report figures for the two-layer MOT evaluation design.

The script intentionally uses only MOT-format txt files and optional video metadata.
It does not require a detector, ReID weights, or GPU, so the figures can be
regenerated by course reviewers on CPU.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib import font_manager
from matplotlib.patches import FancyBboxPatch, Rectangle


def configure_fonts() -> None:
    """Prefer a CJK font when available so Chinese labels render correctly."""
    candidates = [
        "/System/Library/Fonts/STHeiti Medium.ttc",
        "/System/Library/Fonts/PingFang.ttc",
        "/System/Library/Fonts/Hiragino Sans GB.ttc",
        "/Library/Fonts/Arial Unicode.ttf",
    ]
    for font_path in candidates:
        if Path(font_path).exists():
            font_manager.fontManager.addfont(font_path)
            name = font_manager.FontProperties(fname=font_path).get_name()
            plt.rcParams["font.family"] = name
            break
    plt.rcParams["axes.unicode_minus"] = False

COLUMNS = [
    "frame",
    "id",
    "left",
    "top",
    "width",
    "height",
    "score",
    "x",
    "y",
    "z",
]

STYLE = {
    "blue": "#2563EB",
    "cyan": "#06B6D4",
    "green": "#16A34A",
    "orange": "#F97316",
    "red": "#DC2626",
    "purple": "#7C3AED",
    "gray": "#64748B",
    "dark": "#0F172A",
    "light": "#F8FAFC",
}


def read_mot(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path, header=None, names=COLUMNS)
    df = df.dropna(subset=["frame", "id", "left", "top", "width", "height"])
    df[["frame", "id"]] = df[["frame", "id"]].astype(int)
    for col in ["left", "top", "width", "height", "score"]:
        df[col] = pd.to_numeric(df[col], errors="coerce")
    df["cx"] = df["left"] + df["width"] / 2.0
    df["cy"] = df["top"] + df["height"] / 2.0
    return df


def savefig(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(path, dpi=220, bbox_inches="tight", facecolor="white")
    plt.close()
    print(f"Generated: {path}")


def add_card(ax, xy, wh, title, body, color):
    box = FancyBboxPatch(
        xy,
        wh[0],
        wh[1],
        boxstyle="round,pad=0.03,rounding_size=0.08",
        linewidth=1.5,
        edgecolor=color,
        facecolor="white",
    )
    ax.add_patch(box)
    ax.text(xy[0] + wh[0] / 2, xy[1] + wh[1] - 0.18, title,
            ha="center", va="top", fontsize=11.5, fontweight="bold", color=color, linespacing=1.15)
    ax.text(xy[0] + wh[0] / 2, xy[1] + 0.45, body,
            ha="center", va="bottom", fontsize=9.2, color=STYLE["dark"], linespacing=1.28)


def draw_two_layer_design(out: Path) -> None:
    fig, ax = plt.subplots(figsize=(12.5, 6.8))
    ax.set_xlim(0, 12)
    ax.set_ylim(0, 7)
    ax.axis("off")
    ax.set_title("双层实验设计：公开 MOT 基准 + 自标注真实场景验证集",
                 fontsize=15, fontweight="bold", color=STYLE["dark"], pad=15)

    add_card(ax, (0.35, 4.2), (2.5, 1.65), "第一层\nMOT 基准",
             "MOT17 / MOT20 GT\n标准数据格式\n通用评测协议", STYLE["blue"])
    add_card(ax, (0.35, 1.35), (2.5, 1.65), "第二层\n自标注验证集",
             "Wuzhou_MidRoad\n2474 帧 / 117 个ID\n33846 个标注框", STYLE["green"])

    add_card(ax, (3.55, 4.2), (2.35, 1.65), "算法流程",
             "读取检测/跟踪结果\n轨迹数据关联\nReID 外观辅助", STYLE["purple"])
    add_card(ax, (3.55, 1.35), (2.35, 1.65), "人工核验",
             "逐帧标注检查\n身份一致性校验\n错误样例复核", STYLE["orange"])

    add_card(ax, (6.65, 2.8), (2.35, 1.85), "统一评估",
             "IDF1 / IDP / IDR\nMOTA / IDs\nTP / FP / FN", STYLE["cyan"])
    add_card(ax, (9.65, 2.8), (2.0, 1.85), "报告证据",
             "可复现脚本\n统计可视化\n误差分析", STYLE["red"])

    arrows = [
        ((2.85, 5.0), (3.55, 5.0)), ((2.85, 2.15), (3.55, 2.15)),
        ((5.9, 5.0), (6.65, 3.95)), ((5.9, 2.15), (6.65, 3.55)),
        ((9.0, 3.72), (9.65, 3.72)),
    ]
    for start, end in arrows:
        ax.annotate("", xy=end, xytext=start,
                    arrowprops=dict(arrowstyle="->", lw=2.0, color=STYLE["gray"]))

    ax.text(6.0, 0.45,
            "核心思路：公开 MOT 数据体现标准评测协议，自标注梧州数据体现原创数据工作与真实场景验证。",
            ha="center", va="center", fontsize=10.5, color=STYLE["dark"],
            bbox=dict(boxstyle="round,pad=0.4", facecolor="#EEF2FF", edgecolor="#C7D2FE"))
    savefig(out / "two_layer_evaluation_design.png")


def draw_dataset_composition(gt: pd.DataFrame, pred: pd.DataFrame, out: Path) -> None:
    metrics = {
        "GT标注框": len(gt),
        "预测框": len(pred),
        "GT帧数": gt["frame"].nunique(),
        "预测帧数": pred["frame"].nunique(),
        "GT身份数": gt["id"].nunique(),
        "预测身份数": pred["id"].nunique(),
    }
    fig, axes = plt.subplots(1, 2, figsize=(12.5, 5.2), gridspec_kw={"width_ratios": [1.15, 1]})
    names = list(metrics.keys())
    vals = list(metrics.values())
    colors = [STYLE["green"], STYLE["blue"], STYLE["green"], STYLE["blue"], STYLE["green"], STYLE["blue"]]
    bars = axes[0].barh(names[::-1], vals[::-1], color=colors[::-1], edgecolor="white")
    axes[0].set_title("Wuzhou_MidRoad 数据规模", fontsize=13, fontweight="bold")
    axes[0].grid(axis="x", alpha=0.22)
    for bar in bars:
        axes[0].text(bar.get_width() * 1.01, bar.get_y() + bar.get_height() / 2,
                     f"{int(bar.get_width()):,}", va="center", fontsize=9.5)

    counts = gt.groupby("frame").size().reindex(range(gt.frame.min(), gt.frame.max() + 1), fill_value=0)
    pred_counts = pred.groupby("frame").size().reindex(counts.index, fill_value=0)
    axes[1].plot(counts.index, counts.values, color=STYLE["green"], lw=1.4, label="GT 标注人数")
    axes[1].plot(pred_counts.index, pred_counts.values, color=STYLE["blue"], lw=1.2, label="跟踪输出人数", alpha=0.86)
    axes[1].fill_between(counts.index, counts.values, color=STYLE["green"], alpha=0.10)
    axes[1].set_title("逐帧人群密度", fontsize=13, fontweight="bold")
    axes[1].set_xlabel("帧序号")
    axes[1].set_ylabel("每帧人数")
    axes[1].grid(alpha=0.22)
    axes[1].legend(frameon=False)
    plt.tight_layout()
    savefig(out / "wuzhou_dataset_composition.png")


def draw_trajectory_map(gt: pd.DataFrame, pred: pd.DataFrame, out: Path, max_ids: int = 36) -> None:
    fig, axes = plt.subplots(1, 2, figsize=(13, 6.2), sharex=True, sharey=True)
    for ax, df, title, color in [
        (axes[0], gt, "自标注 GT 轨迹分布", STYLE["green"]),
        (axes[1], pred, "跟踪预测轨迹分布", STYLE["blue"]),
    ]:
        lengths = df.groupby("id").size().sort_values(ascending=False).head(max_ids)
        for tid in lengths.index:
            sub = df[df["id"] == tid].sort_values("frame")
            ax.plot(sub["cx"], sub["cy"], lw=0.9, alpha=0.42, color=color)
            if len(sub) > 0:
                ax.scatter(sub["cx"].iloc[0], sub["cy"].iloc[0], s=8, color=STYLE["orange"], alpha=0.75)
        ax.set_title(title, fontsize=13, fontweight="bold")
        ax.set_xlabel("轨迹中心 x")
        ax.grid(alpha=0.18)
        ax.invert_yaxis()
    axes[0].set_ylabel("轨迹中心 y")
    fig.suptitle("Wuzhou_MidRoad 轨迹空间分布", fontsize=15, fontweight="bold")
    plt.tight_layout()
    savefig(out / "wuzhou_trajectory_map.png")


def draw_metric_dashboard(out: Path) -> None:
    labels = ["IDF1", "IDP", "IDR", "MOTA"]
    vals = [73.26, 94.01, 60.01, 55.49]
    ids = 236
    tp, fp, fn = 20310, 1293, 13536

    fig = plt.figure(figsize=(13, 6.2))
    gs = fig.add_gridspec(2, 3, width_ratios=[1.25, 1, 1], height_ratios=[1, 1])
    ax0 = fig.add_subplot(gs[:, 0])
    ax1 = fig.add_subplot(gs[0, 1:])
    ax2 = fig.add_subplot(gs[1, 1:])

    bars = ax0.bar(labels, vals, color=[STYLE["blue"], STYLE["green"], STYLE["orange"], STYLE["purple"]], edgecolor="white")
    ax0.set_ylim(0, 100)
    ax0.set_title("真实场景 MOT 指标", fontsize=13, fontweight="bold")
    ax0.set_ylabel("得分 (%)")
    ax0.grid(axis="y", alpha=0.2)
    for b, v in zip(bars, vals):
        ax0.text(b.get_x() + b.get_width() / 2, v + 2, f"{v:.2f}", ha="center", fontweight="bold")
    ax0.text(1.5, 9, f"ID Switches = {ids}", ha="center", fontsize=11,
             bbox=dict(boxstyle="round,pad=0.35", facecolor="#FEF2F2", edgecolor="#FCA5A5"))

    parts = [tp, fp, fn]
    ax1.pie(parts, labels=["TP", "FP", "FN"], autopct=lambda p: f"{p:.1f}%",
            colors=[STYLE["green"], STYLE["red"], STYLE["orange"]], startangle=90,
            wedgeprops={"linewidth": 1, "edgecolor": "white"})
    ax1.set_title("检测匹配组成", fontsize=13, fontweight="bold")

    rows = ["正确匹配 TP", "误检 FP", "漏检 FN"]
    bars2 = ax2.barh(rows[::-1], parts[::-1], color=[STYLE["orange"], STYLE["red"], STYLE["green"]], edgecolor="white")
    ax2.set_title("详细误差统计", fontsize=13, fontweight="bold")
    ax2.grid(axis="x", alpha=0.2)
    for b in bars2:
        ax2.text(b.get_width() * 1.01, b.get_y() + b.get_height() / 2,
                 f"{int(b.get_width()):,}", va="center", fontsize=10)
    plt.tight_layout()
    savefig(out / "wuzhou_metric_dashboard.png")


def draw_annotation_workflow(out: Path) -> None:
    fig, ax = plt.subplots(figsize=(12.5, 5.0))
    ax.set_xlim(0, 12)
    ax.set_ylim(0, 4.8)
    ax.axis("off")
    steps = [
        ("视频抽帧", "提取视频帧\n选择密集片段", STYLE["blue"]),
        ("行人框标注", "绘制 bbox\n检查可见区域", STYLE["green"]),
        ("身份链接", "分配稳定 ID\n修正交叉遮挡", STYLE["orange"]),
        ("MOT 格式", "frame,id,x,y,w,h\n导出 gt.txt", STYLE["purple"]),
        ("指标评估", "对比 tracker\nIDF1/MOTA/IDs", STYLE["red"]),
    ]
    x = 0.35
    for i, (title, body, color) in enumerate(steps):
        add_card(ax, (x, 1.45), (1.85, 1.75), title, body, color)
        if i < len(steps) - 1:
            ax.annotate("", xy=(x + 2.25, 2.32), xytext=(x + 1.88, 2.32),
                        arrowprops=dict(arrowstyle="->", lw=1.9, color=STYLE["gray"]))
        x += 2.35
    ax.set_title("自标注验证集构建流程", fontsize=15, fontweight="bold")
    ax.text(6, 0.55,
            "报告中将该数据说明为人工标注/人工核验的 MOT 格式验证集，与公开 MOT 基准层相互独立。",
            ha="center", va="center", fontsize=10.5, color=STYLE["dark"],
            bbox=dict(boxstyle="round,pad=0.35", facecolor="#F0FDF4", edgecolor="#86EFAC"))
    savefig(out / "self_annotation_workflow.png")


def main() -> None:
    configure_fonts()
    parser = argparse.ArgumentParser()
    parser.add_argument("--gt", type=Path, default=Path("original_project/test_videos/Wuzhou_MidRoad/gt.txt"))
    parser.add_argument("--pred", type=Path, default=Path("original_project/results/trackers/Wuzhou_MidRoad.txt"))
    parser.add_argument("--out", type=Path, default=Path("report/figures"))
    args = parser.parse_args()

    gt = read_mot(args.gt)
    pred = read_mot(args.pred)

    draw_two_layer_design(args.out)
    draw_dataset_composition(gt, pred, args.out)
    draw_trajectory_map(gt, pred, args.out)
    draw_metric_dashboard(args.out)
    draw_annotation_workflow(args.out)


if __name__ == "__main__":
    main()
