#!/usr/bin/env python3
"""Generate the ReID training curve from the recorded training log.

Unlike a synthetic/smoothed illustration, this script parses
``original_project/run_logs/reid_training_log.txt`` directly.  The report figure
therefore matches the checkpoint summary and can be regenerated by reviewers.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib import font_manager


def configure_fonts() -> None:
    candidates = [
        "/System/Library/Fonts/STHeiti Medium.ttc",
        "/System/Library/Fonts/PingFang.ttc",
        "/System/Library/Fonts/Hiragino Sans GB.ttc",
        "/Library/Fonts/Arial Unicode.ttf",
    ]
    for font_path in candidates:
        if Path(font_path).exists():
            font_manager.fontManager.addfont(font_path)
            plt.rcParams["font.family"] = font_manager.FontProperties(fname=font_path).get_name()
            break
    plt.rcParams["axes.unicode_minus"] = False
    plt.rcParams["font.size"] = 10


ROW_RE = re.compile(
    r"^\s*(?P<epoch>\d+)\s+"
    r"(?P<loss>\d+(?:\.\d+)?)\s+"
    r"(?P<map>\d+(?:\.\d+)?)\s+"
    r"(?P<lr>\d+(?:\.\d+)?)\s+"
    r"(?P<time>\d+(?:\.\d+)?)s\s*$"
)
BEST_RE = re.compile(r"Best model saved at epoch\s+(?P<epoch>\d+)\s+with\s+mAP@?0?\.?5?:\s+(?P<map>\d+(?:\.\d+)?)")
META_RE = re.compile(r"^(?P<key>Model|Dataset|Optimizer|Batch Size|Image Size):\s*(?P<value>.+)$")


def parse_training_log(path: Path):
    rows = []
    meta = {}
    best = None
    for line in path.read_text(encoding="utf-8").splitlines():
        m = ROW_RE.match(line)
        if m:
            rows.append({
                "epoch": int(m.group("epoch")),
                "loss": float(m.group("loss")),
                "map": float(m.group("map")),
                "lr": float(m.group("lr")),
                "time": float(m.group("time")),
            })
            continue
        b = BEST_RE.search(line)
        if b:
            best = {"epoch": int(b.group("epoch")), "map": float(b.group("map"))}
            continue
        mm = META_RE.match(line)
        if mm:
            meta[mm.group("key")] = mm.group("value")
    if not rows:
        raise ValueError(f"No epoch rows found in {path}")
    if best is None:
        best_row = max(rows, key=lambda r: r["map"])
        best = {"epoch": best_row["epoch"], "map": best_row["map"]}
    return rows, best, meta


def generate_curve(log_path: Path, output_path: Path) -> None:
    rows, best, meta = parse_training_log(log_path)
    epochs = [r["epoch"] for r in rows]
    losses = [r["loss"] for r in rows]
    maps = [r["map"] for r in rows]
    lrs = [r["lr"] for r in rows]

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10.5, 8.0), sharex=True)

    ax1.plot(epochs, losses, "o-", color="#2563EB", linewidth=1.8, markersize=4, label="Training Loss")
    ax1.set_ylabel("Loss", fontsize=11, color="#2563EB")
    ax1.tick_params(axis="y", labelcolor="#2563EB")
    ax1.grid(True, alpha=0.25)
    ax1.set_title("ReID 模型训练过程：Loss 下降与验证 mAP 提升", fontsize=14, fontweight="bold")

    ax1_twin = ax1.twinx()
    ax1_twin.plot(epochs, lrs, "s--", color="#16A34A", linewidth=1.4, markersize=3.5, label="Learning Rate")
    ax1_twin.set_ylabel("Learning Rate", fontsize=11, color="#16A34A")
    ax1_twin.tick_params(axis="y", labelcolor="#16A34A")
    ax1_twin.set_yscale("log")

    lines1, labels1 = ax1.get_legend_handles_labels()
    lines2, labels2 = ax1_twin.get_legend_handles_labels()
    ax1.legend(lines1 + lines2, labels1 + labels2, loc="upper right", frameon=False)

    ax2.plot(epochs, maps, "o-", color="#DC2626", linewidth=1.8, markersize=4, label="Validation mAP")
    ax2.set_xlabel("Epoch", fontsize=11)
    ax2.set_ylabel("mAP", fontsize=11, color="#DC2626")
    ax2.tick_params(axis="y", labelcolor="#DC2626")
    ax2.grid(True, alpha=0.25)
    ax2.set_ylim(0, max(0.7, max(maps) + 0.04))

    ax2.axvline(best["epoch"], color="#64748B", linestyle="--", alpha=0.55)
    ax2.axhline(best["map"], color="#64748B", linestyle="--", alpha=0.55)
    ax2.scatter([best["epoch"]], [best["map"]], color="#FACC15", s=180, marker="*", edgecolors="black", zorder=5)
    ax2.annotate(
        f"Best epoch {best['epoch']}\nmAP={best['map']:.4f}",
        xy=(best["epoch"], best["map"]),
        xytext=(max(epochs[0], best["epoch"] - 55), best["map"] + 0.055),
        arrowprops=dict(arrowstyle="->", color="#64748B"),
        bbox=dict(boxstyle="round,pad=0.3", facecolor="#FEF3C7", edgecolor="#F59E0B", alpha=0.9),
        fontsize=10,
    )
    ax2.legend(loc="lower right", frameon=False)

    model = meta.get("Model", "OSNet-AIN / MobileNet Hybrid")
    dataset = meta.get("Dataset", "Market1501 + MSMT17")
    optimizer = meta.get("Optimizer", "SGD with Cosine Annealing")
    batch = meta.get("Batch Size", "32")
    image_size = meta.get("Image Size", "256x128")
    fig.text(
        0.5,
        0.01,
        f"Log file: {log_path.as_posix()} | Model: {model} | Dataset: {dataset} | Optimizer: {optimizer} | Batch={batch}, Image={image_size}",
        ha="center",
        fontsize=8.5,
        color="#475569",
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    plt.tight_layout(rect=(0, 0.035, 1, 1))
    plt.savefig(output_path, dpi=180, bbox_inches="tight", facecolor="white")
    plt.close()
    print(f"Generated: {output_path}")
    print(f"Best mAP: {best['map']:.4f} at epoch {best['epoch']}")


def main() -> None:
    configure_fonts()
    parser = argparse.ArgumentParser()
    parser.add_argument("--log", type=Path, default=Path("original_project/run_logs/reid_training_log.txt"))
    parser.add_argument("--out", type=Path, default=Path("report/figures/training_curve_reid.png"))
    args = parser.parse_args()
    generate_curve(args.log, args.out)


if __name__ == "__main__":
    main()
